
enum Realm
{
    "Aqshy",
    "Azyr",
    "Chamon",
    "Ghur",
    "Ghyran",
    "Hysh",
    "Shyish",
    "Ulgu"
};

enum PlayerId
{
    "None",
    "Red",
    "Blue"
};

enum Verbosity
{
    "Silence",
    "Normal",
    "Narrative",
    "Debug"
};

enum ParamType
{
    "Boolean",
    "Integer",
    "Enum",
};

interface Unit {
    void Unit();

    long points();
    void restore();
};

interface ManoAMano {
    void ManoAMano(long numRounds, Realm realm);
    void combatants(Unit red, Unit blue);
    void start();
    void simulate();
    void next();
    boolean done();
    long currentRound();
    void logStatistics();
    PlayerId getVictor();
};

interface ParameterJS {
    attribute ParamType paramType;
    attribute DOMString name;
    attribute long intValue;
    attribute long minValue;
    attribute long maxValue;
    attribute long increment;
};

interface JSInterface {
    static void Initialize();
    static long GrandAllianceStringToKeyword(DOMString allianceName);
    static long FactionStringToKeyword(DOMString factionName);
    [Const] static DOMString FactionKeywordToString(long faction);
    [Const] static DOMString ParameterValueToString([Ref] ParameterJS param);
};
