
enum Realm
{
    "Aqshy",
    "Azyr",
    "Chamon",
    "Ghur",
    "Ghyran",
    "Hysh",
    "Shyish",
    "Ulgu"
};

enum PlayerId
{
    "None",
    "Red",
    "Blue"
};

enum ParamType
{
    "Boolean",
    "Integer",
    "Enum",
};

interface Wounds {
    void Wounds();

    attribute long normal;
    attribute long mortal;
};

interface Model {
    float x();
    float y();

    boolean slain();
    boolean fled();
};

interface Weapon {
    void Weapon();

    [Const] DOMString nameC();
    long range();
    long attacks();
    long toHit();
    long toWound();
    long rend();
    long damage();
    boolean isMissile();
    float strength();
};

interface Unit {
    void Unit();

    long wounds();
    long move();
    long bravery();
    long save();

    long points();
    long remainingModels();
    long remainingWounds();
    long remainingPoints();
    float basesizeInches();
    float x();
    float y();

    void restore();

    long numModels();
    [Const] Model getModel(long which);

    long getNumWeapons();
    [Const] Weapon getWeapon(long which);
};

interface UnitStatistics {
    void UnitStatistics();

    long numberOfRoundsMoved();
    long numberOfRoundsRan();
    long numberOfRoundsCharged();

    // Totals
    float totalMovementDistance();
    float averageMovementDistance();
    float totalRunDistance();
    float averageRunDistance();
    float totalChargeDistance();
    float averageChargeDistance();

    long totalSavesMade();
    long totalSavesFailed();

    long totalEnemyModelsSlain();
    void totalWoundsInflicted([Ref] Wounds wounds);

    long totalModelsSlain();
    void totalWoundsTaken([Ref] Wounds wounds);

    long totalModelsFled();
};

interface ManoAMano {
    void ManoAMano(long numRounds, Realm realm);
    void combatants(Unit red, Unit blue);
    void start();
    void simulate();
    void next();
    boolean done();
    long currentRound();
    void getStatistics(PlayerId which, [Ref] UnitStatistics stats);
    void clearStatistics();
    PlayerId getVictor();
    float getInitialRedX();
    float getInitialRedY();
    float getInitialBlueX();
    float getInitialBlueY();
    float getBoardWidth();
    float getBoardDepth();
};

interface Parameter {
    void Parameter();
    attribute ParamType paramType;
    [Const] attribute DOMString name;
    attribute long intValue;
    attribute long minValue;
    attribute long maxValue;
    attribute long increment;
};

interface JSUnitInfo {
    void JSUnitInfo();
    [Const] attribute DOMString name;
    attribute long numberOfParameters;
    void getParameter(long which, [Ref] Parameter param);
    attribute long grandAlliance;
    attribute long numberOfFactions;
    long getFaction(long which);
};

interface JSInterface {
    static void Initialize();
    static long GrandAllianceStringToKeyword(DOMString allianceName);
    static long FactionStringToKeyword(DOMString factionName);
    [Const] static DOMString GrandAllianceKeywordToString(long ga);
    [Const] static DOMString FactionKeywordToString(long faction);

    static Unit CreateUnit(DOMString name);
    static long AddUnitParameter([Ref] Parameter parameter);
    static void ClearUnitParameters();
    static long GetNumberOfAvailableUnits();
    static void GetUnitInfo(long which, [Ref] JSUnitInfo info);
    static void GetUnitInfoByName([Const] DOMString name, [Ref] JSUnitInfo info);
    [Const] static DOMString UnitParameterValueToString([Const] DOMString unitName, [Const] DOMString paramName, long paramValue);
    static long UnitEnumStringToInt([Const] DOMString name, [Const] DOMString enumString);
    static long GetUnitPoints([Const] DOMString name, long numModels);
};
